name: build

on: workflow_dispatch

jobs:
  build-ios:
    strategy:
      fail-fast: false
      matrix:
        name:
          - ios-arm64
          - ios-x64
          # - ios-catalyst-arm64
          # - ios-catalyst-x64
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build openssl
        run: |
          cd ${{ github.workspace }}/build-openssl-ios
          chmod +x ./build.sh
          chmod +x ./build_openssl_dist.sh
          ./build.sh
          ls ${HOME}/Desktop/openssl-ios-dist/
      - name: Build
        run: make -C build USE_CCACHE=0 ${{ matrix.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.name }}.tar.xz
          path: package/libwebrtc-${{ matrix.name }}.tar.xz

  release:
    name: Release
    needs:
      - build-ios
    runs-on: macos-11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: libwebrtc-ios-arm64.tar.xz

      - uses: actions/download-artifact@v2
        with:
          name: libwebrtc-ios-x64.tar.xz

      # - uses: actions/download-artifact@v2
      #   with:
      #     name: libwebrtc-ios-catalyst-arm64.tar.xz

      # - uses: actions/download-artifact@v2
      #   with:
      #     name: libwebrtc-ios-catalyst-x64.tar.xz

      # - name: Unpack
      #   run: |
      #     mkdir -p libwebrtc-ios-arm64
      #     tar -Jxvf libwebrtc-ios-arm64.tar.xz -C libwebrtc-ios-arm64
      #     mkdir -p libwebrtc-ios-x64
      #     tar -Jxvf libwebrtc-ios-x64.tar.xz -C libwebrtc-ios-x64
      #     mkdir -p libwebrtc-ios-catalyst-arm64
      #     tar -Jxvf libwebrtc-ios-catalyst-arm64.tar.xz -C libwebrtc-ios-catalyst-arm64
      #     mkdir -p libwebrtc-ios-catalyst-x64
      #     tar -Jxvf libwebrtc-ios-catalyst-x64.tar.xz -C libwebrtc-ios-catalyst-x64

      - name: Unpack
        run: |
          mkdir -p libwebrtc-ios-arm64
          tar -Jxvf libwebrtc-ios-arm64.tar.xz -C libwebrtc-ios-arm64
          mkdir -p libwebrtc-ios-x64
          tar -Jxvf libwebrtc-ios-x64.tar.xz -C libwebrtc-ios-x64

      - name: Merge library ios
        run: |
          cp -r libwebrtc-ios-arm64 libwebrtc-ios
          lipo -create libwebrtc-ios-arm64/lib/libwebrtc.a \
            libwebrtc-ios-x64/lib/libwebrtc.a \
            -output libwebrtc-ios/lib/libwebrtc.a
          cd libwebrtc-ios
          tar -Jcvf libwebrtc-ios.tar.xz include lib NOTICE VERSION
          cd ..

      # - name: Merge library ios catalyst
      #   run: |
      #     cp -r libwebrtc-ios-catalyst-arm64 libwebrtc-ios-catalyst
      #     lipo -create libwebrtc-ios-catalyst-arm64/lib/libwebrtc.a \
      #       libwebrtc-ios-catalyst-x64/lib/libwebrtc.a \
      #       -output libwebrtc-ios-catalyst/lib/libwebrtc.a
      #     cd libwebrtc-ios-catalyst
      #     tar -Jcvf libwebrtc-ios-catalyst.tar.xz include lib NOTICE VERSION
      #     cd ..

      # - name: Publish artifact
      #   uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "build${{ github.run_number }}"
      #     prerelease: false
      #     files: |
      #       libwebrtc-ios-arm64.tar.xz
      #       libwebrtc-ios-x64.tar.xz
      #       libwebrtc-ios-catalyst-arm64.tar.xz
      #       libwebrtc-ios-catalyst-x64.tar.xz
      #       libwebrtc-ios/libwebrtc-ios.tar.xz
      #       libwebrtc-ios-catalyst/libwebrtc-ios-catalyst.tar.xz
      - name: Publish artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "build${{ github.run_number }}"
          prerelease: false
          files: |
            libwebrtc-ios-arm64.tar.xz
            libwebrtc-ios-x64.tar.xz
            libwebrtc-ios/libwebrtc-ios.tar.xz
